# Generated by Django 3.0.4 on 2021-07-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blue_diamonds',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='green_diamonds',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='purple_diamonds',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='yellow_diamonds',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
