# Generated by Django 3.0.4 on 2020-10-01 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_contactmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedcrypto',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
