# Generated by Django 3.0.4 on 2020-10-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_acceptedcrypto_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmethod',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
