# Generated by Django 3.0.4 on 2020-10-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_description',
            field=models.TextField(blank=True, max_length=2500),
        ),
    ]
