# Generated by Django 3.0.4 on 2020-10-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20201002_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmethod',
            name='url_link',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
