# Generated by Django 3.0.4 on 2020-10-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20201021_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmethod',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
