# Generated by Django 3.0.4 on 2020-10-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20201028_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedcrypto',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
