# Generated by Django 3.0.4 on 2020-10-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_acceptedcrypto_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
