version: "3.0"

services:
  client:
    env_file:
      - .env
    build: ./client
    volumes:
      - ./client/src:/app/client/src
      - ./static/assets/build:/app/client/build
  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: backend.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - client
volumes:
  postgres_data: {}
