# Generated by Django 3.0.4 on 2020-12-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
