# Generated by Django 3.0.4 on 2020-03-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_accepted_cryptos'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='accepted_cryptos',
            field=models.ManyToManyField(related_name='accepted_cryptos', to='courses.AcceptedCrypto'),
        ),
    ]
