# Generated by Django 3.0.4 on 2021-07-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210313_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('COURSE', 'Course'), ('EVENT', 'Event'), ('EXAM', 'Exam')], max_length=50),
        ),
    ]
