# Generated by Django 3.0.4 on 2020-09-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200921_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='other_platform',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
