# Generated by Django 3.0.4 on 2020-09-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_event_other_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_reccurrent',
            new_name='is_recurrent',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('COURSE', 'Course'), ('EVENT', 'Event')], max_length=50),
        ),
    ]
