# Generated by Django 3.0.4 on 2021-07-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210705_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_recorded',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('COURSE', 'Course'), ('EVENT', 'Event'), ('EXAM', 'Exam'), ('PRE-RECORDED', 'Pre-Recorded')], max_length=50),
        ),
    ]
