# Generated by Django 3.0.4 on 2021-07-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210707_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('LIVE_COURSE', 'Live_Course'), ('EVENT', 'Event'), ('EXAM', 'Exam'), ('PRE_RECORDED', 'Pre_Recorded')], max_length=50),
        ),
    ]
