# Generated by Django 3.0.4 on 2020-10-01 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200928_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_recorded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.ConnectionPlatform'),
        ),
    ]
