# Generated by Django 3.0.4 on 2020-10-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20201001_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reference_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
