# Generated by Django 3.0.4 on 2020-11-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20201030_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time_zone',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
