# Generated by Django 3.0.4 on 2020-11-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20201124_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
