# Generated by Django 3.0.4 on 2020-11-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_certificaterequest_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
